"""schema update

Revision ID: f0f0bcc655ab
Revises: 
Create Date: 2025-11-29 03:52:47.858303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0f0bcc655ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add the column as nullable temporarily
    op.add_column('report_templates', sa.Column('folder_id', sa.String(), nullable=True))
    op.add_column('report_templates', sa.Column('folder_name', sa.String(), nullable=True))
    op.add_column('report_templates', sa.Column('meta', sa.JSON(), nullable=True))

    # Step 2: Assign a default folder for old rows
    op.execute("UPDATE report_templates SET folder_id = 'default', folder_name = 'Default Folder'")

    # Step 3: Set NOT NULL constraint now that all rows are filled
    op.alter_column('report_templates', 'folder_id', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_templates_template_name'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_folder_id'), table_name='report_templates')
    op.drop_column('report_templates', 'meta')
    op.drop_column('report_templates', 'folder_name')
    op.drop_column('report_templates', 'folder_id')
    op.create_table('template_folders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('template_folders_pkey'))
    )
    op.create_index(op.f('ix_template_folders_id'), 'template_folders', ['id'], unique=False)
    op.create_table('report_folders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('folder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('report_folders_pkey'))
    )
    op.create_index(op.f('ix_report_folders_id'), 'report_folders', ['id'], unique=False)
    op.create_index(op.f('ix_report_folders_folder_id'), 'report_folders', ['folder_id'], unique=True)
    # ### end Alembic commands ###
